### ISSUE TITLE
SqlBatchOperation::Execute - The framework bug workaround isn't appropriate anymore

### ISSUE THREAD

**Issue by pushrbx** [ayende/rhino-etl#8]
Passing in a guid parameter in to the SqlCommand isn't appropriate anymore. (MSSQL2008, .NET4)
I get the following exception:
```
02/09/2015 11:38:36 [ERROR] Rhino.Etl.Core.Pipelines.ThreadPoolPipelineExecuter - Failed to execute operation MyApp.File.Database.Operations.CleanProjectDbOperation
System.ArgumentException: Specified parameter name 'd1073a63-fd4f-4650-9f9e-8fceda004c7f' is not valid.
   at System.Data.SqlClient.SqlCommandSet.Append(SqlCommand command)
   at Rhino.Etl.Core.Infrastructure.SqlCommandSet.Append(SqlCommand command)
   at Rhino.Etl.Core.Operations.SqlBatchOperation.<Execute>d__4.MoveNext()
   at Rhino.Etl.Core.Enumerables.SingleRowEventRaisingEnumerator.MoveNext()
   at Rhino.Etl.Core.Enumerables.EventRaisingEnumerator.MoveNext()
   at Rhino.Etl.Core.Pipelines.ThreadPoolPipelineExecuter.<>c__DisplayClass1.<DecorateEnumerableForExecution>b__0(Object )
```
That part at least need a check if the mentioned bug is present in the current runtime or not and the add the extra guid parameter.

**Comment by ayende** [comment]
Please create a PR for this

**Comment by pushrbx** [comment]
PR added. I've enclosed the details in it.
